### ISSUE TITLE
Cannot Produce Correct Soap Envelope Heading With Contracts

### ISSUE THREAD

**Issue by isaacholden** [DigDes/SoapCore#867] opened 2022-04-20 09:11 UTC
I need to produce the following Soap Envelope with the contracts:

`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/" xmlns:end="omitted" xmlns:xp="omitted">`

But using DataContractSerializer and Soap12WSAddressingAugust2004 produces the contracts but with the wrong heading:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" ......`

if I change to XmlSerializer and keep Soap12WSAddressingAugust2004  I get the correct heading but then the contracts are removed.

I've tried so many different combinations, but cannot produce the first Soap Envelope heading with the contracts.

I'm using SoapCore 1.1.0.28 in a .NET Core 3.1 application.

All my Soap requests were generated using SoapUI by adding the WSDL.

**Comment by andersjonsson** [comment] 2022-04-20 12:00
If I am correct this is a duplicate of #825
@greekoctopus is working on a PR that I hope will fix your issue as well

**Closed by andersjonsson** 2022-04-20 12:00 UTC
