### ISSUE TITLE
ArrayOfString maxOccurs 1

### ISSUE THREAD

**Issue by Griboedoff** [DigDes/SoapCore#988] opened 2024-01-16 19:22 UTC
Hi!

```html
<xsd:complexType name="ArrayOfString">
    <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="1" name="string" type="xsd:string"/>
    </xsd:sequence>
</xsd:complexType>
```
For unknown reason when I use SoapCore `ArrayOfString` in wsdl generated with `maxOccurs="1"` instead of `maxOccurs="unbounded"` attribute like it generates in WCF.
I'm using xmlSerializer

What info I could provide?

**Comment by andersjonsson** [comment] 2024-01-18 07:44
That's odd. In my own services ArrayOfString gets `maxOccurs="unbounded"` as expected.
What is the signature of the methods/objects with string-collections?

My suggestion would be to fork the repo, setting up a test with a small service to reproduce your issue. 
That way you can debug into MetaBodyWriter and see what's going on

**Comment by Griboedoff** [comment] 2024-01-21 08:36
In sample projects I use 
```csharp
[ServiceContract]
public class WebService
{
    [OperationContract]
    public void DoStuff(string[] arrayArg) {}
}
```


Ok, I'll try to fork when I have time to tinker it a bit)

**Comment by vidrenning** [comment] 2024-01-30 16:35
I am able to reproduce this issue and uploaded a pull request for a fix. It is a regression of #960. I also added a test that can be used to reproduce this issue and verify that it is now fixed.

**Closed as completed** 2024-01-31 12:44 UTC

**Comment by Alexcei88** [comment] 2024-02-09 10:59
I have updated to the _1.1.0.43_ version and still see the same issue. It looks like the problem have not been fixed.

**Comment by vidrenning** [comment] 2024-02-09 11:20
It works for me. Please give a small reproducible example of your issue.

**Comment by Alexcei88** [comment] 2024-02-09 12:00
The contract of the service is the same as above one attached by [Griboedoff](https://github.com/Griboedoff). 
The serializer is overriden to xml

` options.SoapSerializer = SoapSerializer.XmlSerializer; `

If I will switch to the default value (DataContract serializer), it is ok.

**Comment by vidrenning** [comment] 2024-02-09 12:04
Just tested it again with v1.1.0.43 and the example class above. This is what I get:

```xml
<xsd:complexType name="ArrayOfString">
  <xsd:sequence>
    <xsd:element minOccurs="0" maxOccurs="unbounded" name="string" type="xsd:string" />
  </xsd:sequence>
</xsd:complexType>
```

As you can see, it shows `maxOccurs="unbounded"`. Are you sure that you are using the newest version of the package? Are you looking at the right place for the ArrayOfString definition?

**Comment by Alexcei88** [comment] 2024-02-09 12:07
Oh, sorry, Looks like it was the old version of library. Now it works.
